commandTopic: "cmd_vel"
odometryTopic: "odom"
odometryFrame: "odom"
robotBaseFrame: "base_link"
publishWheelTF: true
publishOdomTF: true
publishWheelJointState: true
wheelSeparation: 0.34
wheelDiameter: 0.15
wheelAcceleration: 0
wheelTorque: 5
updateRate: 100
odometrySource: 1
leftJoint: "left_wheel_joint"
rightJoint: "right_wheel_joint"

